### ISSUE TITLE
[Deploy]

### ISSUE THREAD

**Issue by vtiffenberg** [instedd/raci#16]
Hablar con @spalladino dónde se guardan las imágenes subidas por usuarios y cómo evitar que se pierdan al hacer deploy con docker.

**Comment by spalladino** [comment]
Lo más sencillo es guardarlas directamente en un campo binary en postgres. Gemas como paperclip creo que facilitan bastante el asunto.

La otra opción es guardarlas en un bucket de S3, pero si esto va a estar hosteado en algún entorno no AWS después, no conviene tanto.

**Comment by vtiffenberg** [comment]
Decidimos dejarlas en una carpeta del file system
