### ISSUE TITLE
Link de logos en encabezado se extiende por debajo de la linea divisora

### ISSUE THREAD

**Issue by pmallol** [instedd/raci#8]
Versión b0daff1

1. Acceder a https://raci-stg.instedd.org/
2. Mover el puntero del mouse un poco por debajo de la línea divisora entre encabezado y contenido

Obtenido:
El .logo-container sobresale por debajo del encabezado

**Comment by vtiffenberg** [comment]
Se arregló con alguno de los cambios posteriores
